name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building the application..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Run Tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Asegúrate de que las pruebas pasen antes de desplegar
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Local Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts
          ssh user@your-server-ip "cd /path/to/your/calculadora && git pull origin main && nohup python app.py &"
