name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building the application..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Instala pytest y cualquier otra dependencia

      - name: Run Tests
        run: |
          pytest  # Ejecuta las pruebas

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: echo "Deploying application..."
